### ISSUE TITLE
Fails to install in proxied environment

### ISSUE THREAD

**Issue by ricfeatherstone** [awslabs/aws-servicebroker#10]
Hi, I have a couple of questions around deploying and then using AWS Service Broker

1. In [this](https://aws.amazon.com/blogs/apn/new-features-in-aws-service-broker-for-openshift-and-kubernetes/) blog post it states `allowing customers to leverage new features such as running behind proxy solutions`. Is there any additional configuration required for this?

1. The APBs take the following parameter `SBArtifactS3Bucket` defaulted to `awsservicebroker`. Is this an existing bucket where config is read from, or a bucket where things are stored and therefore must pre-exist and the cluster (masters?) must have access permissions for?

Thanks

**Comment by ricfeatherstone** [comment]
I've followed the instructions [here](https://github.com/awslabs/aws-servicebroker/blob/master/docs/getting-started-openshift.md) to install the SB into an OpenShift cluster.

The cluster runs in a private VPC with internet access via a proxy, all proxy configuration is correct and example catalog items can be launched ok and have the proxy environment variables set correctly.

In order for the SB to install correctly I had to manually add the proxy environment variables to the aws-asb dc. The catalog then shows the various apbs but without images.

When I try to provision an app it fails, and when I try to remove the provisioned service from the project that also fails, and I am now unable to remove the provisioned service, or delete the project

```
TASK [aws-deprovision-apb : Remove Resources] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. 
The error was: botocore.vendored.requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cloudformation.eu-west-1.amazonaws.com', port=443): 
Max retries exceeded with url: / (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x3384650>, 
'Connection to cloudformation.eu-west-1.amazonaws.com timed out. (connect timeout=60)'))
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n 
File \"/tmp/ansible_yUKTvJ/ansible_module_cloudformation.py\", line 508, in <module>\n main()\n 
File \"/tmp/ansible_yUKTvJ/ansible_module_cloudformation.py\", line 452, in main\n 
stack_info = get_stack_facts(cfn, stack_params['StackName'])\n 
File \"/tmp/ansible_yUKTvJ/ansible_module_cloudformation.py\", line 371, in get_stack_facts\n 
stack_response = describe_stacks(cfn, stack_name)\n File \"/tmp/ansible_yUKTvJ/ansible_modlib.zip/ansible/module_utils/cloud.py\", 
line 103, in retry_func\nbotocore.vendored.requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='cloudformation.eu-west-1.amazonaws.com', port=443): 
Max retries exceeded with url: / (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x3384650>, 
'Connection to cloudformation.eu-west-1.amazonaws.com timed out. (connect timeout=60)'))\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

It looks like this is all related to proxy settings not being picked up correctly.

1. Is there missing documentation around installing the AWS SB so that it works behind a proxy?

1. How do you clean after a failed provisioning?

Thanks

**Comment by ricfeatherstone** [comment]
Just read the FAQ re no proxy support.

**Comment by jaymccon** [comment]
@ricfeatherstone I've re-opened this as proxy support is something we'd like to have operational soonest. 

As far as cleaning up failed provisioning resources goes, you could try this workaround:

`for i in $(oc get projects  | grep Terminating| awk '{print $1}'); do echo $i; oc get serviceinstance -n $i -o yaml | sed "/kubernetes-incubator/d"| oc apply -f - ; done`

**Comment by jaymccon** [comment]
Can you also please confirm your OpenShift version as well as the proxy environment variable keys you added ?

**Comment by ricfeatherstone** [comment]
OpenShift Master:  v3.9.0+ba7faec-1 
Kubernetes Master: v1.9.1+a0ce1bc657
Environment variables all lower case
http_proxy
https_proxy
no_proxy
Proxy set in hosts file for Ansible installation and picked up in BuildDefaults, both lower and upper case

**Comment by ricfeatherstone** [comment]
Is proxy support something that should work transparently, or is there additional configuration required?
Also could you confirm where you are with rolling this out? Is this something I could be trying to get resolved now or would have to wait for?

**Comment by ricfeatherstone** [comment]
Hi,
I thought when you reopened this ticket, it was because you were going to help work through the issues to get this resolved.
If it's just going to sit here, open but inactive, I can't see the point and will close.

**Comment by jaymccon** [comment]
@ricfeatherstone apologies for the lag getting back onto this issue. The hope is that on 3.9+ clusters proxying should work with minimal configuration. It's also worth noting that we are in the process of doing a full re-write of the broker code (no eta for completion just yet), which will remove the intermediate pods used to launch services, which should simplify the required configuration.

I am in the process of doing expanded testing using an ocp cluster behind a proxy and will update with my findings in the next couple of days.

**Comment by ricfeatherstone** [comment]
For installation I've added the proxy variables to the service broker dc and installation works. The intermediate pods do not pick up proxy settings and I guess that's the route of the issue.
I'll wait for your response and see where we are following that. If there's no resolution, I suggest we close the ticket and wait for the refactoring (or support for CloudFormation over private link) as it appears at this point, proxy support won't work and as this is stated on the FAQ, technically there is no issue

**Comment by jaymccon** [comment]
I've been able to confirm the issue in my tests, but don't have a workaround for the current release. We are working on a full re-write of the broker core, and all efforts are going towards that release with an aim to have an initial beta available in the repo in the next few weeks. 

The updated broker will no longer use the transient pods for provisioning, which will simplify proxy support, as only the broker pod will need to be configured for a proxy. We are also ensuring that our ci processes are testing against proxied environments to be sure we can properly support this use-case.

**Comment by ricfeatherstone** [comment]
Thanks for the update, that matches my understanding of the issue and as the FAQ currently states proxied environments are not supported I'm happy to close this issue, unless you want it as a reference for anyone else hitting this until the refactoring is complete?

**Comment by ricfeatherstone** [comment]
I'm going to close this now as now there are no intermediate containers, setting the proxy on the broker deployment works.

Would be good to either add parameters to the install scripts for proxy settings or document how to modify the template
