### ISSUE TITLE
Release 1.0.0-beta.4

### ISSUE THREAD

**Issue by calerogers** [awslabs/aws-servicebroker#101]
Hi,

We are looking to make use of passing in tags on the broker deployment as referenced here:
https://github.com/awslabs/aws-servicebroker/issues/68

It doesn't look like the latest tagged version in dockerhub (1.0.0-beta.3) has this feature as it was added after it was published. Would you mind cutting a new release and pushing it there?

Thanks!

**Comment by jaymccon** [comment]
1.0.0.0beta-4 should include this
