### ISSUE TITLE
Cross account / cluster bindings

### ISSUE THREAD

**Issue by chiefy** [awslabs/aws-servicebroker#110]
**Is your feature request related to a problem? Please describe.**
I recently got the broker setup and creating resources in a separate AWS account but there appears to be no way to easily get the bindings from the k8s cluster in account A to the cluster where a service might live in account B.

**Describe the solution you'd like**
Really any solution outside of running a broker in account A _and_ account B would be nice, but since `ServiceBinding` is outside the broker's domain, not entirely sure what to do here.

**Comment by jaymccon** [comment]
Can you expand on your desired work flow a bit ? 

For cross-account the broker supports `target_account_id` and `target_role_name` parameters at provision that provision the service in a different account to what the broker runs in, bind operations for that service are then made against the target account. Not sure if this fits your requirements.

**Comment by chiefy** [comment]
@jaymccon 

> bind operations for that service are then made against the target account. 

But how will the generated secret get into the k8s cluster in the secondary account?

**Comment by jaymccon** [comment]
The idea behind cross account is more to allow segmenting AWS accounts, than k8s clusters. At present the way we see customers using this is to provision the broker in the same cluster that the app that will consume the service resides. The cross account allows multi-tenanting the cluster, with each team having their own AWS account, or providing different AWS accounts for dev/prod deployments.

To use your example, Service Foo should have a broker, ServiceInstance and binding created in EKS-B. During provision. If EKS-A is provisioning a test build of Foo, then it would have it's own, distinct broker, ServiceInstance and binding to it's own RDS instance.

What you could try is to setup both brokers with the same ID's and backing DynamoDB table, that way they share state, potentially allowing a serviceinstance created in EKS-A to be bound from EKS-B. Haven't tested this, and it's unlikely to be something we support, at least in the short term, but might be worth a look if the traditional use case doesn't work for you.

**Comment by chiefy** [comment]
@jaymccon thanks for clearing that up - we were hoping to only have to run one central broker but it looks like that's not the way to do it.
