### ISSUE TITLE
Feature request: RDS Aurora MySQL

### ISSUE THREAD

**Issue by maxenglander** [awslabs/aws-servicebroker#117]
Would like to be able to use AWS SB to provision RDS Aurora clusters. I don't believe this is currently possible with the current `rdsmysql` template, but please correct me if I'm wrong!

**Comment by jaymccon** [comment]
Templates for Aurora are in the works.

cc @ryannikschaws

**Comment by maxenglander** [comment]
Thanks for the quick reply @jaymccon looking forward to trying them.

**Comment by ndrest-amzn** [comment]
Templates added https://github.com/awslabs/aws-servicebroker/tree/master/templates/auroramysql
