### ISSUE TITLE
Question: why pass in CIDR blocks and Availability Zones

### ISSUE THREAD

**Issue by maxenglander** [awslabs/aws-servicebroker#118]
Some templates (such as [ElastiCache](https://github.com/awslabs/aws-servicebroker/blob/master/templates/elasticache/template.yaml) and [RDS MySQL](https://github.com/awslabs/aws-servicebroker/blob/master/templates/rdsmysql/template.yaml)) expect CIDR Blocks, Availability Zones, and VPC ID to be passed in as inputs.

This gives AWS-SB the ability to create subnets for every new ElastiCache or RDS instance, and gives the person(s) who are managing these resources on the K8S-side the ability to carve out large CIDR blocks within a VPC.

Is this the practice that the authors of this project recommend that users of AWS SB adopt? Or is this meant as one possible operational model, and that users of AWS SB are free to choose a different operational model and modify the existing templates to suit their own needs?

**Comment by jaymccon** [comment]
It's one possible model which, based on feedback, we felt was the most common. 

We also envisage many customers having specific requirements that would be hard to handle every variation of in our provided templates. See https://github.com/awslabs/aws-servicebroker/tree/master/docs#custom-catalog for examples on defining your own custom catalog of templates.

**Comment by maxenglander** [comment]
Makes sense @jaymccon thanks for the helpful reply.
