### ISSUE TITLE
Errand deploy-all for AWS Service Broker fails with Response code: 500  

### ISSUE THREAD

**Issue by reddychenna** [awslabs/aws-servicebroker#120]
Running errand deploy-all for AWS Service Broker
===== 2019-06-04 16:01:32 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=ip --deployment=aws-service-broker-be79f7ae1ee07e85b5e5 run-errand deploy-all"

Fails with Waiting for app to start...  
            
          name:              aws-sb-1.0.1  
          requested state:   started  
          routes:            URL  
          last uploaded:     Tue 04 Jun 16:03:58 UTC 2019  
          stack:             cflinuxfs3  
          buildpacks:        binary  
            
          type:            web  
          instances:       1/1  
          memory usage:    1024M  
          start command:   export PARAM_OVERRIDE_${BROKER_ID}_all_all_all_region=${AWS_DEFAULT_REGION} ; export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} ; export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} ; export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} ; ./cfnsb --logtostderr --prescribeOverrides=${PRESCRIBE} --v=${VERBOSITY} --brokerId=${BROKER_ID} --enableBasicAuth=true --insecure=true --port=${PORT} --region=${AWS_DEFAULT_REGION} --s3Bucket=${S3_BUCKET} --s3Key=${S3_KEY} --s3Region=${S3_REGION} --tableName=${TABLE_NAME} --templateFilter=${TEMPLATE_FILTER}  
            
               state     since                  cpu    memory        disk        details  
          #0   running   2019-06-04T16:04:09Z   0.0%   18.8M of 1G   15M of 1G     
          cf app aws-sb-1.0.1   # waiting for running state  
          cf app aws-sb-1.0.1   # waiting for running state  
          cf app aws-sb-1.0.1   # waiting for running state  
          cf app aws-sb-1.0.1   # waiting for running state  
          cf app aws-sb-1.0.1   # waiting for running state  
          cf app aws-sb-1.0.1   # waiting for running state  
          cf create-service-broker aws-sb 63e961986a3041b0 ******** URL
          Creating service broker aws-sb as system_services...  
          Unexpected Response  
          Response code: 500  
          CC code:       0  
          CC error code:   
          Request ID:    0cfea1e3-59d4-48c2-5570-a512f5d06502::855c5c3b-1d87-49a1-8a94-a643fb0d73b8  
          Description:   {  
            "error_code": "UnknownError",  
            "description": "An unknown error occurred.",  
            "code": 10001  
          }  
            
          FAILED  
            
Stderr     Using cflinuxfs3 stack  
            

1 errand(s)

**Comment by jaymccon** [comment]
Are you able to share the logs from the broker app `aws-sb-1.0.1`

**Comment by reddychenna** [comment]
[aws-broker.log](https://github.com/awslabs/aws-servicebroker/files/3277414/aws-broker.log)

Updated aws service broker app log

**Comment by reddychenna** [comment]
Updated the case with latest aws service broker app log.

Please include me at chenna.korvi@shcr.com as well going forward as well in
the email communication.

Thanks, Chenna

**Comment by gtantachuco-pivotal** [comment]
Hey @jaymccon,
When I tried to install the AWS Service Broker v1.0.1 on Pivotal Ops Manager v2.5.6 and Pivotal App Service v2.5.4, I got an HTTP 500 error. Any help you can provide will be greatly appreciated.
Please find attached 2 log files: 1) Service broker app log; and, 2) Ops Manager installation log.
[error-aws-sb-1.0.1.log](https://github.com/awslabs/aws-servicebroker/files/3291507/error-aws-sb-1.0.1.log)
[error-ops-manager.log](https://github.com/awslabs/aws-servicebroker/files/3291508/error-ops-manager.log)

Thank you.

**Comment by jaymccon** [comment]
@gtantachuco-pivotal Is the `error-aws-sb-1.0.1.log` complete ? 

I'd expect to see some more logs from when the broker receives the request to list the available services (which is part of the `cf create-service-broker` process.

perhaps set verbosity on the app up to 10 (in env vars) and re-run the `cf create-service-broker aws-sb d54c7cd04eb0b12a ******** https://aws-sb.apps.mydomain.com` call by hand. You can get the `*****` value from the app environment variables.

**Comment by gtantachuco-pivotal** [comment]
@jaymccon,
I increased the verbosity to 10 but I got the exact same amount of messages. I ran the CloudFormation template (https://github.com/awslabs/aws-servicebroker/blob/master/setup/prerequisites.yaml). 

Is there anything else I need to do or check after running the CloudFormation template to ensure that the installation completes successfully?

**Comment by jaymccon** [comment]
only that the stack has created successfully, and that it is created in the same region that you specified in the region property of the tile.

**Comment by gtantachuco-pivotal** [comment]
Thank you for your help and patience. I am still getting the error.  Please find attached the output. 
[aws-sb-create.txt](https://github.com/awslabs/aws-servicebroker/files/3292264/aws-sb-create.txt)

**Comment by reddychenna** [comment]
> from the logs it looks like your dynamodb table does not exist, has a different name, or is in a different region/account. Have you followed the [prerequisites](https://github.com/awslabs/aws-servicebroker/blob/master/docs/install_prereqs.md) ?
> 
> If the DynamoDb table does exist ensure that the tile configuration contains the correct values for the table name and region.
> 
> ```
> 2019-06-11T10:54:08.57+0000 [APP/PROC/WEB/0] ERR I0611 10:54:08.570003      71 adapter.go:37] putting service definition "athena" into dynamdb
> 2019-06-11T10:54:08.66+0000 [APP/PROC/WEB/0] ERR E0611 10:54:08.658292      71 adapter.go:58] ResourceNotFoundException: Requested resource not found
> ```

@jaymccon, Thanks for the analyzing the data and suggestion. After creating the dynamodb table, I am able to successfully deploy the product to PCF and errand tests were successful. This can be closed.

**Comment by jaymccon** [comment]
@reddychenna great to hear your issue is resolved.

@gtantachuco-pivotal looks like your issue is happening before the broker even gets queried (hence us not seeing anything in the app logs), from the cli output you provided:

```
REQUEST: [2019-06-14T16:12:24-05:00]
POST /v2/service_brokers HTTP/1.1
Host: api.sys.mydomain.com
...
RESPONSE: [2019-06-14T16:12:25-05:00]
HTTP/1.1 500 Internal Server Error
```

so the request to the pcf api `api.sys.mydomain.com/v2/service_brokers` is returning `500` this happens before the broker is involved. I'm no PCF expert, but I think this looks like a problem on your foundation. 

My guess is that you won't be able to even list service-brokers (`cf service-brokers`) on that foundation, as it makes the same api call.

**Comment by gtantachuco-pivotal** [comment]
Thank you. Will take a closer look. I have other tiles installed and when I run `cf service-brokers` in the `system` org, it returns all the brokers that correspond to those tiles. Please feel free to close this issue. Have an awesome weekend, @jaymccon

**Comment by thagh05t** [comment]
I am having the exact same issue in my foundry, possible edge case? I traced the cloud controller logs back to find something like this...

`{
    "error_code": "UnknownError",
    "description": "An unknown error occurred.",
    "code": 10001,
    "test_mode_info": {
        "description": "undefined method `each' for nil:NilClass",
        "error_code": "CF-each",
        "backtrace": [
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/lib/services/service_brokers/v2/catalog.rb: 11:in `initialize'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/lib/services/service_brokers/service_broker_registration.rb: 94:in `new'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/lib/services/service_brokers/service_broker_registration.rb: 94:in `catalog'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/lib/services/service_brokers/service_broker_registration.rb: 85:in `validate_catalog!'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/lib/services/service_brokers/service_broker_registration.rb: 16:in `create'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/app/actions/services/service_broker_create.rb: 34:in `create'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/app/controllers/services/service_brokers_controller.rb: 42:in `create'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/app/controllers/base/base_controller.rb: 86:in `dispatch'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb: 16:in `block in define_route'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1634:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1634:in `block in compile!'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 992:in `block (3 levels) in route!'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1011:in `route_eval'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 992:in `block (2 levels) in route!'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1040:in `block in process_route'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1038:in `catch'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1038:in `process_route'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 990:in `block in route!'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 989:in `each'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 989:in `route!'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1097:in `block in dispatch!'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1076:in `block in invoke'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1076:in `catch'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1076:in `invoke'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1094:in `dispatch!'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 924:in `block in call!'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1076:in `block in invoke'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1076:in `catch'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1076:in `invoke'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 924:in `call!'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 913:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb: 18:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb: 16:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb: 26:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb: 50:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb: 50:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb: 31:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/null_logger.rb: 9:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/head.rb: 12:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 194:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.4/lib/sinatra/base.rb: 1957:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/urlmap.rb: 68:in `block in call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/urlmap.rb: 53:in `each'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/urlmap.rb: 53:in `call'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/middleware/cef_logs.rb: 18:in `call'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/middleware/request_logs.rb: 22:in `call'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/middleware/security_context_setter.rb: 19:in `call'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/middleware/vcap_request_id.rb: 15:in `call'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/middleware/cors.rb: 49:in `call_app'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/middleware/cors.rb: 14:in `call'",
            "/var/vcap/data/packages/cloud_controller_ng/e5bc0734f34b4d799fcb4cc59ca1e058e8f2cf1e/cloud_controller_ng/middleware/request_metrics.rb: 12:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb: 153:in `call'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb: 86:in `block in pre_process'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb: 84:in `catch'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb: 84:in `pre_process'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb: 50:in `block in process'",
            "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb: 1067:in `block in spawn_threadpool'"
        ]
    }
}`

Any insight greatly appreciated.

**Comment by thagh05t** [comment]
Culprit looks like it is:
`[ERR] I0616 20:06:32.980065 75 awsbroker.go:217] Client OSB API Version: "2.14"`

What exactly does this error mean? I am assuming an unsupported API version?

**Comment by thagh05t** [comment]
I have been digging a bit deeper and found that the /v2/catalog endpoint being called by the CC is returning `{"services":null}`. I can only assume this is either a misconfiguration or an issue with the .pivotal release.

**Comment by thagh05t** [comment]
As i understand it, there is an official tile hitting the Tanzu Network within a month, so i wont dwell on the small things. I wasn't understanding why the S3 bucket wasnt being populated with templates and found out that the bucket in the config by default points to an AWS hosted resource already containing the necessary templates. After returning the s3 config to its original state, I was successfully able to apply. Hope this helps someone since this project looks dead.
