### ISSUE TITLE
Why did delivery options removed? (SNS)

### ISSUE THREAD

**Issue by knqyf263** [awslabs/aws-servicebroker#132]
**Describe the bug**
The delivery options of SNS were removed. Why did it do?
https://github.com/awslabs/aws-servicebroker/commit/e6f6f2b3379736ef33fa1f0c1b474a82d900969b#diff-5239f074cbbdcf3e83a9132a86d088c4L126

**Comment by rniksch** [comment]
Would you be so kind as to clarify what you mean? I have taken a look at the changes I am not seeing what you mean by a delivery option being removed?  If you could point me to a code snippet or line number I maybe able to provide insight.

**Comment by knqyf263** [comment]
I'm so sorry, but I forget the detail since it is old. Let me close, please.
