### ISSUE TITLE
Doesn't support china region at this time?

### ISSUE THREAD

**Issue by gyj0825** [awslabs/aws-servicebroker#134]
**Describe the bug**
I've already run aws-servicebroker on openshift 3.11.59 in cn-northwest-1 Region. I can see aws service catalog in openshift webconsole, but can't provision services.

aws-servicebroker error logs as below:
```
E0718 09:27:59.627266       1 api.go:156] TemplateURL: 0xc0003f1570
--
  | E0718 09:27:59.627303       1 api.go:157] Tags: [{
  | Key: "aws-service-broker:broker-id",
  | Value: "awsservicebroker"
  | } {
  | Key: "aws-service-broker:instance-id",
  | Value: "54c19744-a93e-11e9-98b1-0a580a800015"
  | } {
  | Key: "aws-service-broker:cluster",
  | Value: "7dd6b0e4-a792-11e9-996f-0a580a800014"
  | } {
  | Key: "aws-service-broker:namespace",
  | Value: "test"
  | }]
  | E0718 09:27:59.627376       1 api.go:158] StackName: 0xc0003f17b0
  | E0718 09:27:59.627391       1 api.go:159] Parameters: [{
  | ParameterKey: "BucketName",
  | ParameterValue: "my-china-test"
  | } {
  | ParameterKey: "BucketAccessControl",
  | ParameterValue: "Private"
  | } {
  | ParameterKey: "LifeCyclePrefix",
  | ParameterValue: "Archive"
  | } {
  | ParameterKey: "EnableVersioning",
  | ParameterValue: "False"
  | } {
  | ParameterKey: "GlacierLifeCycleTransitionInDays",
  | ParameterValue: "0"
  | } {
  | ParameterKey: "PreventDeletion",
  | ParameterValue: "True"
  | } {
  | ParameterKey: "EnableGlacierLifeCycle",
  | ParameterValue: "False"
  | } {
  | ParameterKey: "LoggingPrefix",
  | ParameterValue: "Archive"
  | } {
  | ParameterKey: "EnableLogging",
  | ParameterValue: "False"
  | }]
  | E0718 09:27:59.627441       1 api.go:160] Capabilities: [0xc0003f1ca0]
  | E0718 09:27:59.627459       1 util.go:308] Status: 500; ErrorMessage: <nil>; Description: Failed to create the CloudFormation stack: ValidationError: TemplateURL must reference a valid S3 object to which you have access.
  | status code: 400, request id: 5520a5c0-a93e-11e9-865a-57ddacddd6a6; ResponseError: <nil>
```

**To Reproduce**
use aws-servicebroker provision services in cn-northwest-1 Region.

**Expected behavior**
provision services in cn-northwest-1 Region

**Environment (please complete the following information):**
 - Application Platform: [OpenShift Container Platform 3.11.59]
 - Application Platform Version: [k8s v1.11.0]
 - Broker Version [2.13]

**Additional context**
I use my S3 bucket in cn-northwest-1 Region. I can't find that how to setup TemplateURL. 

We look forward to your reply，thanks.

**Comment by jaymccon** [comment]
to use the broker in cn regions you will need to copy the templates into a bucket in the same region, then set `s3bucket` and `s3region` to your bucket/region

**Comment by gyj0825** [comment]
yes, i already copy all template to my bucket in the same region. aws-servicebroker can find 18 object，but I can’t create cloudformation stack in aws when provision service.

**Comment by jaymccon** [comment]
@gyj0825 did you resolve this ? if so are you able to provide resolution, should others find this issue.

**Comment by bizzelicious** [comment]
@gyj0825 How did you solve this? I'm running into the same problem.

**Comment by gyj0825** [comment]
@jaymccon @bizzelicious 
The cause of the problem is that the image version in the template is incorrect. I modified it to aws-servicebroker/servicebroker:v1.0.1 and solved it.
