### ISSUE TITLE
deploy.sh script not working on OpenShift 4.1

### ISSUE THREAD

**Issue by sjbylo** [awslabs/aws-servicebroker#139]
deploy.sh script looks in the wrong project since the project name has changed in OCP 4.1 

Created this PR so the script will work on 4.1 as well. 
https://github.com/awslabs/aws-servicebroker/pull/138

**Comment by sjbylo** [comment]
The deploy.sh script needs to look like this, to ensure the objects are created in the "aws-sb" project and not in the kube-service-catalog or the openshift-service-catalog-apiserver projects. 

When I get time, I'll create a PR. 

#!/bin/bash

ACCESSKEYID=$(echo -n $1 | base64)
SECRETKEY=$(echo -n $2 | base64)
# On OpenShift 4.x the project name has changed to "openshift-service-catalog-apiserver"
oc project kube-service-catalog 2>/dev/null || oc project openshift-service-catalog-apiserver 2>/dev/null || echo "Warning: Cannot find project ..."
CA=`oc get secret                         -o go-template='{{ range .items }}{{ if eq .type "kubernetes.io/service-account-token" }}{{ index .data "service-ca.crt" }}{{end}}{{"\n"}}{{end}}' | grep -v '^$' | tail -n 1`
oc new-project aws-sb
oc process -f aws-servicebroker.yaml --param-file=parameters.env -p BROKER_CA_CERT=$CA -p ACCESSKEYID=${ACCESSKEYID} -p SECRETKEY=${SECRETKEY} | oc apply -f -

**Comment by sjbylo** [comment]
I have recently re-deployed AWS Service Broker onto OpenShift 4.1 and I'll send another PR for the 'deploy.sh' script, which should fix this (my mistake) once and for all!

**Comment by rniksch** [comment]
Seems the project has changed names again in OCP 4.2
OCP deploy script has been updated for use in 4.2
