### ISSUE TITLE
Fail to create S3 Bucket 

### ISSUE THREAD

**Issue by Ty-Torregrosa** [awslabs/aws-servicebroker#141]
**Describe the bug**
I cannot deploy an s3 bucket. Through PAS. I get this error
 [APP/PROC/WEB/0] [ERR] status code: 400, request id: 03307eb0-b9f0-11e9-af4a-b16728783c1b; ResponseError: <nil>
[APP/PROC/WEB/0] [ERR] For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
 [APP/PROC/WEB/0] [ERR] E0808 15:20:10.970858 46 util.go:308] Status: 500; ErrorMessage: <nil>; Description: Failed to create the CloudFormation stack: ValidationError: S3 error: Access Denied
[APP/PROC/WEB/0] [ERR] E0808 15:20:10.970811 46 api.go:160] Capabilities: [0xc4203f0820]

Note the access denied with reason, api.go capabilities.

**To Reproduce**
Install PCF Opsman, bosh director and PAS on AWS Govcloud. (quickstart?). Create all prerequisites. Install the AWS Service Broker tile. Upload the default s3 template from this repo to you rs3 bucket.

**Expected behavior**
Deploy s3 bucket using GUI or CLI. All AWS Resources are created by cloudformation template correctly.

**Screenshots**

**Environment (please complete the following information):**
 - Application Platform: Pivotal Cloud Foundry
 - Application Platform Version: 2.3.6
 - Broker Version 1.0.1

**Additional context**

**Comment by kreutziger** [comment]
We have the same issue, but only with creating an RDS database not S3 bucket. DynamoDB, S3 and SQS work without issues, but databases with the default template as well as with a reduced template which does not even interact with foreign buckets and uses administrative rights, gets the same error as above.

[rdsaws.txt](https://github.com/awslabs/aws-servicebroker/files/4060237/rdsaws.txt)

**Comment by tealeg** [comment]
We're also experiencing the same problem, also using Pivotal Cloud Foundry.

**Comment by tealeg** [comment]
@kreutziger I don't think the problem is with an individual template, it seems to be with accessing the template itself via an https:// url.  In the source code this is generated, and I have been able to succesfully validate and create-stack via the command line (`aws cloudformation...`), but the service broker never succeeeds.

**Comment by rniksch** [comment]
I am able to install, configure the AWS Service broker. 
Able to deploy S3, RDS as well as other AWS Services via the broker.

On face value the above seems to be an issue with config of the broker itself. 
Some things to check:
On the Broker Tile config:
A dynamoDB table needs to be created as one of the pre reqs, this was most likely deployed using a CFN template or AWS CLI command within the repo. ensure the table exists and the broker is configured with the correct table name

Amazon DynamoDB table name=awssb

The broker should be running on a PAS / TAS The region should match the region of the DynamoDB table:

AWS REGION=us-east-1
In my case I am using us-west-2
This will be a different region if you are deploying in govcloud.

Where are the service templates stored, this could be the AWS provided bucket or your own S3 bucket. The tile needs the region the bucket exists in, bucket name, and prefix.
Amazon S3BUCKET=awsservicebroker
Amazon S3 Key Prefix=templates/latest
Amazon S3 REGION=us-east-1

If you are deploying your own S3 bucket
The bucketname will change to reflect the bucket you have created.
depending on the structure of the data in the backed you may or may not have a key
and the region would need to match the region you created the bucket in.

My testing I did not create my own S3 bucket. I am not clear on the description above if own S3 buckets for template store have been used.

Finally permission to access all the above.
In PCF there is limited support for AWS IAM roles, so you will be creating a IAM user and 

There is an IAM role used to provision the AWS services this will have permissions on AWS CloudFormation as well as each of the services controlled by the broker. 
The tile is configured with this role:
AWS CloudFormation Role ARN = ...

Then there is a IAM user which is used for running the broker itself , interacting with S3 template store, dynamodb and needs permissions to assume the above role.

In my testing I am using an IAM user so I provided a secret key and access key.
In the time these are: 
AWS Access key id
AWS secret key id

you will want to check the policies attached to these.
I think the following may be helpful:
https://pcf-on-aws.awsworkshop.io/30-aws-service-broker-install-and-config/1_readme.html

**Comment by kreutziger** [comment]
> @kreutziger I don't think the problem is with an individual template, it seems to be with accessing the template itself via an https:// url. In the source code this is generated, and I have been able to succesfully validate and create-stack via the command line (`aws cloudformation...`), but the service broker never succeeeds.

The strange thing is, I can do that as well, and even if I gave the aws service broker user administrative rights, the broker could not deploy the RDS resources. Everything else is working fine. If I create the RDS CloudFormation stack myself, that is also working.

I have to check @rniksch comments.

**Comment by tealeg** [comment]
@rniksch we are deploying in eu-central-1 and have an s3 bucket int the same region.  We have carefully followed the available instructions on how to set up the aws-servicebroker, but still, we see this issue.  The custom S3 bucket is clearly a candidate for the source of the issue, but we're not yet able to find out why exactly.  Current status on my part - I've forked the repo and I'm adding some additonal logging to try  and get a better idea of what is happening.

**Comment by tealeg** [comment]
We have solved our problem.  The name of the template YAML file *must* be the value of the name field within the file, plus the configured prefix and then ".yaml".  For example if you have a template for `rdspostgresql`, with than Name configured in the template, and a prefix of "-main" then the YAML file you upload to S3 *must* be called `postgresql-main.yaml` - anything else will result in this failure.

**Comment by rniksch** [comment]
> We have solved our problem. The name of the template YAML file _must_ be the value of the name field within the file, plus the configured prefix and then ".yaml". For example if you have a template for `rdspostgresql`, with than Name configured in the template, and a prefix of "-main" then the YAML file you upload to S3 _must_ be called `postgresql-main.yaml` - anything else will result in this failure.

I will update docs and blogs to call this out more specifically.
This should only be a factor for custom created templates.

**Comment by rniksch** [comment]
There are two sets of issues being discussed here:
1) customer templates and customer catalog i.e storing in your own catalog
2) General install and config of the broker using provided catalog.
