### ISSUE TITLE
Elasticsearch serviceinstance does not support GP2 storage

### ISSUE THREAD

**Issue by lerrigatto** [awslabs/aws-servicebroker#146]
**Describe the bug**
I am trying to provision a custom ES with gp2 storage but the `AllocatedStorageAndIops` requires IOPS and ES fails if you pass iops on a gp2 volume.

**To Reproduce**
It should be enough to deploy a GP2 storage with all defaults. But this is the manifest I am trying to apply.
```apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: elasticsearch-custom-load-testing
spec:
  clusterServiceClassExternalName: elasticsearch
  clusterServicePlanExternalName: custom
  parameters:
    AccessCidr: XXX
    EngineVersion: 2.3
    NodeAvailabilityZones: 2
    NodeInstanceType: m4.large.elasticsearch
    DedicatedMasterInstanceType: t2.medium.elasticsearch
    DedicatedMasterInstanceCount: 3
    StorageType: gp2
    NodeToNodeEncryption: false
    EncryptionAtRest: false
    ESDomainName: load-test-es
```

**Expected behavior**
I expect aws-servicebroker to provision ES with gp2 storage

**Relevant logs**
```
E0829 13:27:59.426566       1 util.go:308] Status: 400; ErrorMessage: CloudFormationError; Description: ElasticsearchDomain Iops is only valid when volume type is io1. (Service: AWSElasticsearch; Status Code: 400; Error Code: ValidationException; Request ID: blablabla-yadayayada-requestid) ; ResponseError: <nil>
```

**Environment (please complete the following information):**
 - Application Platform: Kubernetes, provisioned by KOPS
 - Application Platform Version: v1.11.6
 - Broker Version: chart: aws-servicebroker--1.0.1

**Comment by ndrest-amzn** [comment]
Created PR to address issue where selecting GP2 or standard would also populare the IOPS value causing the template to fail.
