### ISSUE TITLE
Amazon MQ - creating password, does not support special chars

### ISSUE THREAD

**Issue by ndrest-amzn** [awslabs/aws-servicebroker#148]
**Describe the bug**
When the password is created using the MQ template: _https://github.com/awslabs/aws-servicebroker/tree/master/templates/mq_

The password is autogenerated, and sometimes inserting characters unsupported by Amazon MQ's password policy: 
_Make sure your password doesn't contain invalid characters [, :=]._

**Resolution**
To resolve please alter the password generating Lambda function to not include these characters found here:
_https://s3-eu-west-1.amazonaws.com/awsservicebrokeralpha/functions/generate_password/lambda_function.zip/functions/generate_password/lambda_function.zip_

Alter line 12 of the _lambda_function.py_ from

` special_characters= "-;:,.<>?[]{}_=+~!%^()"`

to 

` special_characters= "-;.<>?{}_+~!%^()"`

**Comment by jaymccon** [comment]
function updated as a stop gap. This custom resource will be removed in favour of Secrets Manager. Tracked in #149
