### ISSUE TITLE
Service Request: Elasticsearch

### ISSUE THREAD

**Issue by abursavich** [awslabs/aws-servicebroker#18]
Support for AWS Elasticsearch Service would help with bootstrapping logging infrastructure in new clusters.

**Comment by jaymccon** [comment]
This is a high priority service to add support for and will be in the next batch of service updates.

**Comment by hassbert** [comment]
Hi there
@jaymccon is there any update on this topic?

**Comment by jaymccon** [comment]
cc @ndrest-amzn 

Support for this service is still on our radar, but I have no timelines to share at this time.

**Comment by jaymccon** [comment]
added in 74a9190446f469d81df15ee7e815f52ae246e0a3
