### ISSUE TITLE
CloudFormation Templates are out of date, is the project active ?

### ISSUE THREAD

**Issue by raj-gl** [awslabs/aws-servicebroker#186]
Hi,

We would like to provide easy access to aws resources for our self-serviced developer portal.

We would like to know whether this project is still considered as the official one to provision AWS resources for end customers. We are worried because the last release was 10 months ago and some of the cloud formation templates are out-of-date. For Example: https://github.com/awslabs/aws-servicebroker/blob/master/templates/rdsmysql/template.yaml (It doesnt contain the latest version or instance type)

We would like to contribute to the project, but we need to know if the project is actively developed and supported. 

Regards,
Raj

**Comment by jeohist** [comment]
We have the same concerns, and considering it's been three weeks since this issue was created with no response, it doesn't exactly instill confidence.

**Comment by HerrmannHinz** [comment]
any news?

**Comment by juv** [comment]
Maybe the operator pattern and hence this project got more traction internally?  
https://github.com/aws/aws-service-operator-k8s

**Comment by kferrone** [comment]
Yeah the aws-service-operator is going to get the attention eventually. Unfortunately the repo posted above is only docs and conversations and actual code is a long way off. I have read somewhere mentioning the plan but now I can't find the article anymore. It was some aws blog article somewhere. 

However this project works like a charm for us. Once you understand Cloudformation enough, make your own templates. The default broker templates are kinda weak and outdated so we made our own which wasn't too hard. Making your own gives way better control and ours are much simpler than the ones provided. 

Even if the operator becomes the more popular option, it still won't be as versatile as this project with CFN templates. With this you can customize the templates however you want. The point of the operator is to provide `K8S Custom Resources` which would not makes sense to map to a hand made CFN template, so be cautious when comparing the broker to the operator. 

 I believe on reason it doesn't get much love is the [Service Catalog (OSB API)](https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/) is still kinda young too and is still in Beta. 

Please do keep it alive if you can!

**Comment by rniksch** [comment]
The CFN templates which cater for service plans in the broker do not have a 1:1 parity with the AWS services. Customer feedback is collected and based on this features and updates are done. this may see new services added or existing ones updated. New services on the road map include MSK, SNS, elasti cache redis, comprehend. RDS, DynamoDb, will be getting updates to support new features and versions.

**Comment by rniksch** [comment]
This project is still being supported with a focus on Cloud foundry based systems.
we are seeing a move towards operator based solutions for Kubernettes based solutions.

**Comment by mekza** [comment]
It would make more sense to move away from CloudFormation templates and use [aws-cdk](https://github.com/aws/aws-cdk)

**Comment by mekza** [comment]
@rniksch how come this issue was closed?
