### ISSUE TITLE
Extensions API Deprecated and probably aws-servicebroker too

### ISSUE THREAD

**Issue by kferrone** [awslabs/aws-servicebroker#189]
Just sayin, I got the error below when upgrading to EKS 1.16 using the Helm chart

> no matches for kind "Deployment" in version "extensions/v1beta1"

K8s 1.16 removed the extensions/Deployment API and it was deprecated since version 1.9!  All we need is to have the deployment have `apiVersion: apps/v1`. I would gladly fix this simple issue and make a PR but it doesn't seem any issues or PRs get addressed anymore. 

Please AWS, say something . . . Either put a big ol `DEPRECATED` banner or give the project some love. I also see the [kubernetes-sigs/service-catalog](https://github.com/kubernetes-sigs/service-catalog) doesn't get much attention either. Seems like [k8s OSBAPI](https://www.openservicebrokerapi.org/) is on life support. Wheres the doctor at? 

The only other possible AWS managed alternative to this project is [aws/aws-service-operator-k8s](https://github.com/aws/aws-service-operator-k8s). Looks promising but no code and no commits or even a word for two months?! Soooo .... not an alternative yet.  

At least [SageMaker Operator](https://github.com/aws/amazon-sagemaker-operator-for-k8s) and [Appmesh Controller](https://github.com/aws/aws-app-mesh-controller-for-k8s) get some love. EKS in general is getting love. It's even getting love with CDK and Eksctl.

From the world of open source I did find some non AWS managed solutions:
 - [linki/cloudformation-operator](https://github.com/linki/cloudformation-operator)
    - tl;dr review: the entire CFN template is just a string?!

aaand that seems to be it  . . . Please respond if you know of anything else. 

If this project is dead and there are no comparable alternatives, then I fear I must say goodbye. 😞

Basically I know what I must do, if I must say goodbye:

**Not** so easy option 1:
 1. make a secret with vars which I was injecting with param override feature from this project
     - e.g. AccessCidr, VpcId, various ARNs to useful lambda functions
 2. make helm chart with job/cron-job in it using the [amazon/aws-cli](https://hub.docker.com/r/amazon/aws-cli) docker image
 3. bind to step 1 secret with `envFrom: common-cfn-vars`
 4. One of these to get env vars to template param mapping with [aws cli cloudformation](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/index.html)
    * do something hacky, painful, and magical to have one job to rule them all 
    * skip the magic and make a job per template . . . 
  5. Within the main job or a successive one get the output and make a secret, like the ServiceBinding does
  
**Not** so fun option 2:
We use Gitlab CI at work. Was using Gitlab Ci to deploy my super cool Helm charts with Broker Templates made for this project and tuned to our clusters. I guess I could just deploy the CFN templates with Gitlab-CI . . . Not much different from option 1 but with less automation. Same story for the many other CI tools I've used before . . . bunch o Bash, yay. 

**Maybe** fun option 3:
Give [linki](https://github.com/linki/cloudformation-operator) a shot. Probably this one . . . 

**God Mode** option 4:
Take over this project as a maintainer or even take a stab at [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) and make something innovative. Unfortunately, I'm just a mortal  . . .

Please o please have a conversation with me community on what can be done. What projects/alternatives have ya'll considered? Any insight as to why this project went silent? Could it simply be covid causing a lack of attention? Maybe Amazon could say what's up and maybe even pass the torch?

**Comment by miguelaferreira** [comment]
@kferrone My team is in a similar situation, depending on this project, making contributions and hearing very little to nothing when asking for support from the maintainers. 

A colleague of mine opened this PR over 6 months ago https://github.com/awslabs/aws-servicebroker/pull/163

Meanwhile I've making an [alternative to service catalog and brokers using terraform](https://github.com/miguelaferreira/k8s-terraform-module-controller). The project is in its infancy, but I'm looking for a good reason to dedicate more time to it.
