### ISSUE TITLE
Does the aws-servicebroker installation support SSO authentication based installation in PCF?

### ISSUE THREAD

**Issue by ichandan16** [awslabs/aws-servicebroker#193]
Hi Team,
We have a PCF-2.8.5 foundation and we are trying to install aws-servicebroker 1.0.1.
The installation fails at cf-create-broker step where it needs to talk to login.SYS_DOMAIN for authentication.

I have attached the log file. Replaced the DOMAINs and auth_username value from the log.
[create-sb-step.log](https://github.com/awslabs/aws-servicebroker/files/4748139/create-sb-step.log)

Question:
1. Is this tile works if SAML Identity provider is enabled in PCF?

Appreciate your help.

Best Regards,
Chandan Patra

**Comment by rniksch** [comment]
The broker itself will make use of IAM user access key  secret key or role to auth to AWS.
As for users connecting to the PCF TAS foundation they do not need AWS access they need to authentication and authorization on the PCF TAS foundation. so SSO to login either cf CLI and then the role based access control within PCF will control access to the broker and services.

If I have miss under stood please let me know.
