### ISSUE TITLE
AWSSBInjectedGetCidrs Failed to create resource. Not enough available space in the vpc

### ISSUE THREAD

**Issue by ichandan16** [awslabs/aws-servicebroker#194]
Hi, I am trying to create a rdsmysql instance from Pivotal Cloud Foundry (PCF) using aws-servicebroker. The command goes like this (I have changed the VPCID and AccessCidr values) :

`cf -v create-service rdsmysql dev test-rdsmysql -b aws-sb -c '{"VpcId":"vpc-0abcd1234efgh","AccessCidr":"22.33.44.0/24","region":"us-east-1"}'`

The failure message : 
``` 
status:    create failed
message:   AWSSBInjectedGetCidrs Failed to create resource. 
           Not enough available space in the vpc 
```
Appreciate any help.

Thanks,
Chandan Patra

**Comment by rniksch** [comment]
The RDS plan will create new subnets within the vpc defined. 
The parameters you provide would include:

NumberOfAvailabilityZones
This is how many AZs the RDS would span, the broker would create a new subnet for each.
AvailabilityZones
this is default auto meaning the broker will use any of the AZs mapped to your account or you can specifically define them
CidrSize
the is the subnet to be created listed in CIDR prefix notation i,e /24, /28 etc

possible subnet related failures:
if using the defaults the broker will create three subnets each having a /27 within the existing address space.
depending on the vpc being used there may not be enough address space to cater for this.
I think this is the case here

The RDS templates do not at this stage cater for deploying into existing subnets, work is being done to cater for this and you will likely see addition rds and elsticache options for deployment into existing subnets. this requires modification of the parameter, metadata, and resource sections of the templates should you wish to make this modification in your own custom catalog.
