### ISSUE TITLE
Long time no release

### ISSUE THREAD

**Issue by CVirus** [awslabs/aws-servicebroker#196]
It has been over a year now since aws-servicebroker had a release. There are multiple merged PR's that are really useful and would make a release. Please consider this.

Thanks!

**Comment by CVirus** [comment]
or at least push the latest templates to the `awsservicebroker` bucket

**Comment by rniksch** [comment]
The latest release is 1.0.1 this was pushed out 3 day ago.
to my knowledge the latest templates are in s3, if you are seeing something missing please would you be so kind as to call it out specifically, and I will dig into that

**Comment by CVirus** [comment]
Thanks!
