### ISSUE TITLE
SQS FIFO Queue Creation Failed - PCF

### ISSUE THREAD

**Issue by thagh05t** [awslabs/aws-servicebroker#197]
**Describe the bug**
SQS FIFO queue creation fails:
`SQSQueue The name of a FIFO queue can only include alphanumeric characters, hyphens, or underscores, must end with .fifo suffix and be 1 to 80 in length.`

There is no parameter for QueueName so it looks like one is generated. After generation, because this is a fifo queue, I assume .fifo is appended which may cause the name length to go out of bounds. [Possibly related to this.](https://github.com/aws/aws-cdk/issues/5860)

**To Reproduce**
- Install as instructed in PCF.
- create a fifo queue through the cf cli.

**Expected behavior**
Successful service creation.

**Screenshots**
Error pasted above.

**Environment (please complete the following information):**
 - Application Platform: PCF
 - Application Platform Version: 2.5.4
 - Broker Version 1.0.1

**Additional context**
I can assume this is easily resolved with a change to the templates hosted by AWS, is there someone here that manages it?

**Comment by rniksch** [comment]
I am investigating
will see if I am able to reproduce

**Comment by rafilkmp3** [comment]
Hi @rniksch  this is still happening with minimal and complete example is failing 
![image](https://user-images.githubusercontent.com/12433667/115801642-9c331900-a3b3-11eb-9abb-28b3a03aed53.png)

**Comment by rafilkmp3** [comment]
Its impossible create a fifo queue
