### ISSUE TITLE
Can I bind existing resource?

### ISSUE THREAD

**Issue by kevmando** [awslabs/aws-servicebroker#204]
Hi,

We already have RDS instance for prod, and are migrating our apps to K8S.
So I'd like to only bind the existing RDS instance thru broker, but not provisioning new instance/restore to avoid downtime.

Is it possible with current broker?

**Comment by rniksch** [comment]
No the AWS Service broker is only able to manage resources provisioned by the broker. 
Secondly for K8 you may want to explore the Amazon Controller for Kubernettes, this might be a better fit.
