### ISSUE TITLE
Push to CF fails for aws service broker - ./cfnsb: No such file or directory

### ISSUE THREAD

**Issue by shwetankverma** [awslabs/aws-servicebroker#207]
**Describe the bug**
Push to CF fails for aws service broker.
./cfnsb: No such file or directory

**To Reproduce**
After modifying the manifest.yaml when CF push command is fired, it fails. 
Error -- **ERR bash: ./cfnsb: No such file or directory**

**Expected behavior**
CF Push should pass

**Screenshots**

**Environment (please complete the following information):**
 - Application Platform: Cloud Foundry (SAP Cloud Plaform)
 - Application Platform Version: [e.g. k8s 1.11.0]
 - Broker Version - v1.0.2

**Additional context**

**Comment by tealeg** [comment]
You can't just push the application, as is.  "cfnsb" is the name given to the compile binary when you build a tile from the source - if you try and build using the go buildpack, for example, you'll get a different binary name (normally something like `servicebroker`).  Getting to the point where you can start from the source repository and just do a `cf push` with a manifest is quite hard.

**Comment by shwetankverma** [comment]
i got it...
