### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by pjfbashton** [awslabs/aws-servicebroker#215]
With the recent announcement of [ACK](https://aws.amazon.com/blogs/containers/aws-controllers-for-kubernetes-ack/) I was wondering what is the roadmap for this project?

**Comment by tealeg** [comment]
@pjfbashton a very good question.  I would hope that the service broker will still be maintained as ACK is not useful to CloudFoundry users.

**Comment by rniksch** [comment]
That is correct ACK is a better fit for Kubernettes, The AWS service broker is intended to continue being supported for CloudFoundry users. That said customers with CloudFoundry running on kubernettes may have choice in the future.
