### ISSUE TITLE
Unable to set region for ServiceInstances

### ISSUE THREAD

**Issue by cyrus-mc** [awslabs/aws-servicebroker#33]
**Describe the bug**

I am installing the service broker into a k8s cluster via the provided helm chart as instructed in the documentation.

An inspect of the chart parameters shows value aws.region, which defaults to us-east-1. For my install I set to us-west-2 and the expectation was that ServiceInstances would be deployed in that region. That is not the case and they still get deployed into us-east-1. 

**To Reproduce**

Install the broker via the official helm chart.

helm install aws-sb/aws-servicebroker --name aws-servicebroker --namespace aws-sb --version 1.0.0-beta --set aws.region=us-west-2 --set aws.accesskeyid=xxxxx --set aws.secretkey=xxxxxx --set aws.vpcid=vpc-XXXXX

**Expected behavior**

As there is no documentation that explains exactly what the values control I was operating under the assumption that the region defined the region for the ServiceInstances. If that is the case my expectation would be that Cloudformation stacks would be created in the region specified (us-west-2 in my case) not us-east-1.

**Environment (please complete the following information):**
 - Application Platform: Kubernetes
 - Application Platform Version: v1.10.5 
- Broker Version: 1.0.0-beta

**Comment by cyrus-mc** [comment]
Did some digging through the code. 

Option --region sets the region, but this doesn't appear to be correctly set via the helm chart. Therefore it always defaults to us-east-1.

The chart does take a value aws.region and that ends up setting environment variable AWS_DEFAULT_REGION and PARAM_OVERRIDE_awsservicebroker_all_all_all_region but I am not sure what those control at this point.

**Comment by vsomayaji** [comment]
@jaymccon I think there are a couple issues here.

When we create the CFN client, we use the `region` from the `AwsBroker`:

https://github.com/awslabs/aws-servicebroker/blob/93ce57d0a37e853a311fc49049e57680f7c808be/pkg/broker/api.go#L133

And that's set with the `region` CLI arg:

https://github.com/awslabs/aws-servicebroker/blob/c3eb18ff980423151a783448b9e763c14db867e0/pkg/broker/cli.go#L13

Issue 1: `region` is not being set in the Helm template:

https://github.com/awslabs/aws-servicebroker/blob/2b7ba36304216375237a1a92bfadf5738668d6ed/packaging/helm/aws-servicebroker/templates/broker-deployment.yaml#L30-L59

Issue 2: If the `region` is set as a param or an override, it's not used.

**Comment by cyrus-mc** [comment]
@vsomayaji 

I validated what I posted and you confirmed by setting the region CLI argument on the broker and it correctly created stacks in the specified region.

Simple fix to the helm chart and I can fork and PR back. 

But as stated, not sure what the ENV variables controlled as they were set to the value specified for the helm chart.

**Comment by vsomayaji** [comment]
@cyrus-mc thanks for investigating! Re: the env vars:

1. I don't think `AWS_DEFAULT_REGION` is used and could be removed. @jaymccon can you confirm?

2. Some of the plans have a `region` param that will override the `region` CLI arg. `PARAM_OVERRIDE_awsservicebroker_all_all_all_region` is the way to globally override the `region` param (the override naming convention is `PARAM_OVERRIDE_<brokerID>_<cluster>_<namespace>_<service>_<paramName>`). However, it looks like the region override is broken, both at the instance and global level. ☹️ We'll get that fixed.

**Comment by jaymccon** [comment]
Yep, AWS_DEFAULT_REGION is not needed as wherever sessions are being created we're explicitly setting region.
