### ISSUE TITLE
Credentials for provisioning ServiceInstances doesn't appear to default to what is used for broker operations. 

### ISSUE THREAD

**Issue by cyrus-mc** [awslabs/aws-servicebroker#35]
**Describe the bug**

According to the install_prereqs.md document:

"By default the broker will use the same credentials for provisioning ServiceInstances and for broker operations like fetching the catalog and reading/writing metadata to DynamoDB."

But I don't believe I am seeing that behavior. I have a role assigned to the k8s node that the broker is running on (with the required IAM policies as instructed in the documentation). This allows the broker to start-up, fetch catalog, etc.

Start-up Log:

`
I0925 21:13:40.225027       1 util.go:212] Did not find 'aws_access_key' and 'aws_secret_key' in params, using default chain.
I0925 21:13:40.225091       1 aws_sdk.go:63] Parameter 'target_role_name' not set. Not assuming role.
I0925 21:13:40.225117       1 util.go:212] Did not find 'aws_access_key' and 'aws_secret_key' in params, using default chain.
I0925 21:13:40.225131       1 aws_sdk.go:63] Parameter 'target_role_name' not set. Not assuming role.
I0925 21:13:40.634674       1 awsbroker.go:38] Running as caller identity '{
  Account: "755621335444",
  Arn: "arn:aws:sts::XXXXXX:assumed-role/k8s-dev-node-20180917031935213600000001/i-0f3d92fd704eb2cfe",
  UserId: "AROAJWLLVCXBHEGTXKLMK:i-0f3d92fd704eb2cfe"
}'.
`

However when I go to provision a SerivceInstance it errors stating that aws_access_key and aws_secret_key can not be blank.  I then have to deploy the chart specifying aws.accesskeyid and aws.secretkey.

**To Reproduce**

Install official helm chart:helm install aws-sb/aws-servicebroker --name aws-servicebroker --namespace aws-sb --version 1.0.0-beta --set aws.region=us-west-2 --set aws.vpcid=vpc-XXXXX

And leave out the aws.accesskeyid and aws.secretkey.

**Expected behavior**

As per the documentation the serviceinstance provisioning should default to the same credentials as the broker.

**Environment (please complete the following information):**
 - Application Platform:k8s
 - Application Platform Version: v1.10.5
 - Broker Version 1.0.0-beta

**Comment by cyrus-mc** [comment]
Figured I would start digging through the code again and I think this is due to getRequiredParams that parses the plan and determines what are the required parameters?

I looked through the SQS latest template (since that is what I am trying to deploy) and don't see any required parameters for that Stack.

**Comment by vsomayaji** [comment]
@cyrus-mc yep, you're right on. You can see the required params for the `sqs` class at s3://awsservicebroker/templates/latest/sqs-spec.yaml (the spec is generated from https://github.com/awslabs/aws-servicebroker/blob/master/templates/sqs/template.yaml, and the generator adds the `aws_access_key`, `aws_secret_key`, and `region` params).

@jaymccon the generator is currently marking `aws_access_key` and `aws_secret_key` as `required: true`, which means that `Provision` will fail if they're not set:

https://github.com/awslabs/aws-servicebroker/blob/93ce57d0a37e853a311fc49049e57680f7c808be/pkg/broker/api.go#L94-L99

Can the generator be updated to mark them as `required: false`? Alternatively, we can tweak `getRequiredParams` to ignore non-CFN params. What do you think?

**Comment by jaymccon** [comment]
@vsomayaji I'll update the generator and public templates to address this. While I can't think of a use-case offhand it may be useful at some point to have required non-CFN params.

**Comment by vsomayaji** [comment]
@jaymccon awesome. Can you also update the generator to add the `target_role_name` and `target_account_id` params? They could be useful for customers that don't want to give the broker pod god credentials or want to provision resources in a different account.

**Comment by cesartl** [comment]
I've got a similar issue. I've installed the aws service broker with following https://aws.amazon.com/blogs/opensource/provision-aws-services-kubernetes-aws-service-broker/. I wasn't able to install the aws service broker with helm because of #37 

I can see I have a `aws-secret` created which has value for `region`, `VpcId` etc... however when I create any of the service instance I see error in the logs about missing parameters `region`. It seems that those parameters are not being fetched from the secret. Now sure how I can investigate further.

**Comment by jaymccon** [comment]
I've updated the public templates in `s3://awsservicebroker/templates/latest` removing the required for `aws_access_key` and `aws_secret_key`, also added parameters for `target_role_name` and `target_account_id`. 

@cyrus-mc @vsomayaji @cesartl can you please validate this solves the issue for you

I'm thinking updating the generator is a bigger job to do it right. Ideally I'd like to get rid of it entirely and get the broker to read everything it needs straight from the template. I'll open a seperate issue to discuss and get feedback on the approach.

**Comment by vsomayaji** [comment]
@jaymccon I reviewed a couple of the updated specs and verified that `target_account_id` and `target_role_name` were added and that none of the non-CFN params are required. And re: eliminating the generator, I think that's a great idea. 👍 

@cyrus-mc can you verify that your issue has been resolved?

@jaymccon re: @cesartl's issue, the Helm install failure (https://github.com/awslabs/aws-servicebroker/issues/29) should be resolved now, correct? Or does that require a release? I think the [blog  post](https://aws.amazon.com/blogs/opensource/provision-aws-services-kubernetes-aws-service-broker/) he used installs the _old_ version of the AWS Service Broker, which could explain the errors.

**Comment by jaymccon** [comment]
@cesartl this should be addressed in the latest beta.2 release
