### ISSUE TITLE
`bosh-release` repo is not a proper submodule, causes issues on recursive clone

### ISSUE THREAD

**Issue by mook-as** [awslabs/aws-servicebroker#39]
**Describe the bug**
There is a [`bosh-release` directory](https://github.com/awslabs/aws-servicebroker/tree/master/bosh-release) that holds a reference to a `aws-servicebroker-boshrelease` sub-repository that is not a submodule (there's no `.gitmodules` file at the top level).

**To Reproduce**
```
$ git submodule update --init --recursive
fatal: No url found for submodule path 'bosh-release/aws-servicebroker-boshrelease' in .gitmodules
```

**Expected behavior**
Either a valid submodule pointer, or no sub-repository in the tree.

**Environment (please complete the following information):**
`master` as of 100cc6beb021bafa23f2f5883afaa946b1a073f8 — no other configuration should be necessary.

**Additional context**
I can ignore the error on clone fine, it's just annoying because my [CI system](https://concourse-ci.org/) (amusingly from Pivotal) tries to recurse by default and falls splat on its face.  Currently working around the issue by telling it to ignore _all_ submodules, which works for now (but will break if there's an actual submodule we care about in the future).

**Comment by jaymccon** [comment]
Thanks for raising this @mook-as, should be resolved with  60ebe08
