### ISSUE TITLE
Postgres RDS fails with missing MasterPassword

### ISSUE THREAD

**Issue by lcostea** [awslabs/aws-servicebroker#42]
**Describe the bug**
I followed the tutorial from here:
https://aws.amazon.com/blogs/opensource/provision-aws-services-kubernetes-aws-service-broker/
I was able to provision a SQS, but on a Postgres RDS it always fails with:

```
TASK [aws-provision-apb : Encode bind credentials] *****************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'MasterPassword'\n\nThe error appears to have been in '/opt/ansible/roles/aws-provision-apb/tasks/main.yml': line 95, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  when: create_iam_user == true\n- asb_encode_binding:\n  ^ here\n"}
 [WARNING]: Could not create retry file '/opt/apb/actions/provision.retry'.
[Errno 13] Permission denied: u'/opt/apb/actions/provision.retry'

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=2    unreachable=0    failed=1
```
**To Reproduce**
Followed the tutorial from 
https://aws.amazon.com/blogs/opensource/provision-aws-services-kubernetes-aws-service-broker/

Modified the broker-config ConfigMap to include also the 
`- {apb_name: dh-rdspostgresql, secret: aws-secret, title: aws-secret}`
This way I saw that the Postgres RDS ServiceInstance was able to use the aws-secret.

But no matter if I added the field:
`MasterUserPassword: $n2w7dWbPDP3 `
or didn't use it at all I always got the same error.

This is the ServiceInstance I used:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: dev-k8s-local-rds-postgresql
spec:
  clusterServiceClassExternalName: dh-rdspostgresql
  clusterServicePlanExternalName: dev
  parameters:
    AccessCidr: 172.20.0.0/16 # REQUIRED
    AllocatedStorageAndIops: 100 GB / 1,000 IOPS # OPTIONAL
    DBInstanceClass: db.t2.medium # OPTIONAL
    EngineVersion: 9.6.3 # OPTIONAL
    PostgresServerTimezone: UTC # OPTIONAL
    MasterUsername: postgres-rds-user
    MasterUserPassword: $n2w7dWbPDP3
```

Removing MasterUsername and MasterUserPassword leads to the same error.

**Expected behavior**

I should be able to create an Postgres RDS

**Environment (please complete the following information):**
Kubernetes Kops Cluster on AWS
Kubernetes version: 1.10.5

**Comment by lcostea** [comment]
Browsing through the code, it looks like this has nothing to do with Postgres password, but it is about credentials for AWS. 
But I still can't see where this MasterPassword is coming

**Comment by jaymccon** [comment]
@lcostea Can you please try to re-install the broker using the [docs](https://github.com/awslabs/aws-servicebroker/tree/master/docs). The blog you mentioned is outdated (I'm in the process of trying to get the author to update it).

**Comment by lcostea** [comment]
Are there other resources where I can find information about the setup and the AWS Service Broker in general? 
Installing with the docs is not that easy, for me it seems that there are missing pieces and I am trying to figure out how all of them fit together.

**Comment by lcostea** [comment]
I managed to create a Postgresql RDS using the AWS Service broker.
Thanks!
