### ISSUE TITLE
Waiting for a ServiceInstance to be provisioned might waste too much time

### ISSUE THREAD

**Issue by lcostea** [awslabs/aws-servicebroker#47]
**Describe the bug**
I noticed that when waiting for a ServiceInstance to be created (async operation), the broker starts with 2 seconds and then increase it exponentially (2, 4, 8, 16, 32 etc). So if you reach the step 512 seconds actually (a little more than 8 minutes) and your cloud formation stack is not ready yet, next you are going to wait for 1024 (more than 16 min). 
Of course this is not critical, but it can delay a running pipeline pretty much, so it can be a nice improvement.

**To Reproduce**
I installed the AWS Service Broker and created a Postgres RDS Service Instance:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: dev-rds-postgresql
spec:
  clusterServiceClassExternalName: rdspostgresql
  clusterServicePlanExternalName: custom
  parameters:
    AccessCidr: 172.20.0.0/16 # REQUIRED
    AllocatedStorageAndIops: 100 GB / 1,000 IOPS # OPTIONAL
    DBInstanceClass: db.t2.medium # OPTIONAL
    EngineVersion: 9.6.3 # OPTIONAL
    PostgresServerTimezone: UTC # OPTIONAL
    MasterUsername: user
    MasterUserPassword: d67sfjs2dknfahD
```
Then checking the broker logs I see:

```
I1005 11:06:25.725980       1 awsbroker.go:239] Client OSB API Version: "2.13"
I1005 11:06:25.726138       1 apisurface.go:89] Received ProvisionRequest for instanceID "b33e3355-c88e-11e8-bf6f-0a5864601c5d"
[...]
I1005 11:06:33.837661       1 awsbroker.go:239] Client OSB API Version: "2.13"
I1005 11:06:33.837690       1 apisurface.go:233] Received LastOperationRequest for instanceID "b33e3355-c88e-11e8-bf6f-0a5864601c5d"
[...]
I1005 11:07:30.072533       1 awsbroker.go:239] Client OSB API Version: "2.13"
I1005 11:07:30.072559       1 apisurface.go:233] Received LastOperationRequest for instanceID "b33e3355-c88e-11e8-bf6f-0a5864601c5d"
[...]
I1005 11:10:42.244319       1 awsbroker.go:239] Client OSB API Version: "2.13"
I1005 11:10:42.244349       1 apisurface.go:233] Received LastOperationRequest for instanceID "b33e3355-c88e-11e8-bf6f-0a5864601c5d"
[...]
I1005 11:14:58.355522       1 awsbroker.go:239] Client OSB API Version: "2.13"
I1005 11:14:58.355550       1 apisurface.go:233] Received LastOperationRequest for instanceID "b33e3355-c88e-11e8-bf6f-0a5864601c5d"
[...]
I1005 11:40:34.586522       1 awsbroker.go:239] Client OSB API Version: "2.13"
I1005 11:40:34.586653       1 apisurface.go:233] Received LastOperationRequest for instanceID "b33e3355-c88e-11e8-bf6f-0a5864601c5d"
[...]
I1005 11:40:34.690669       1 api.go:249] CREATE_COMPLETE
```

I missed some iterations, there were just too many to show. In this case there were around 12 minutes I just waited for the next iteration since the stack was complete.

**Expected behavior**
I think the step should have a max value, like 128 or 256 seconds and stop increasing it after that.
So after it reaches 2-4 minutes for updates, it could stick to that value.

I did try to find the code that handles that, but I don't see where the PollLastOperation from the service-broker-client library is being called.

**Additional context**
Kubernetes Kops Cluster on AWS
Kubernetes version: 1.10.5
Broker Version: 1.0.0-beta.2

**Comment by vsomayaji** [comment]
@jaymccon any thoughts on this? I noticed the same thing when provisioning RDS DB instances, but I think the configuration is on the catalog side. Based on:

https://github.com/kubernetes-incubator/service-catalog/blob/118c04fb3cb4df7c6410f1cd9aef1b3c7b3e8b41/pkg/controller/controller.go#L107

Can this be controlled by setting the `operation-polling-maximum-backoff-duration` flag?

https://github.com/kubernetes-incubator/service-catalog/blob/9768c1a69077112a76606db521e0c8ad459df9b9/cmd/controller-manager/app/options/options.go#L120

The default of 20 minutes does seem high:

https://github.com/kubernetes-incubator/service-catalog/blob/9768c1a69077112a76606db521e0c8ad459df9b9/cmd/controller-manager/app/options/options.go#L62

**Comment by Akynxx** [comment]
"region",
	"target_role_name",
	"target_account_id",
}
 var nonCfnParamDefs = map[string]interface{}{

**Comment by jaymccon** [comment]
@lcostea I've added some guidance to the docs to warn that `operation-polling-maximum-backoff-duration` should be adjusted in service catalog. This is not a configurable value in their helm chart at present, so adding an argument to the deployment after install is the simplest way to reduce the timeout for the time being.
