### ISSUE TITLE
Availability as PCF tile on pivnet?

### ISSUE THREAD

**Issue by aegershman** [awslabs/aws-servicebroker#51]
Apologies for skipping the template, this doesn't quite fit the criteria--

We're under the impression this service broker will be available as a tile compatible with Pivotal's distribution of Cloud Foundry (PCF).

[When do you think we'll see this available as a tile on Pivnet?](https://network.pivotal.io/)

**Comment by jaymccon** [comment]
We do release the broker packaged as a PCF tile, which is currently available from the [releases](https://github.com/awslabs/aws-servicebroker/releases) page. 

Ultimately this should be available from PivNet directly, but we have no timelines for that at present.

**Comment by aegershman** [comment]
I gotcha 👍 We're unable to take this tile to our wider platform audience until this is available on pivnet && out of a `*-beta` release. [We'll have to stick to the existing `aws-services` broker for the moment](https://network.pivotal.io/products/aws-services).  Thanks for your time and work; we'll definitely be keeping eyes close on this repository
