### ISSUE TITLE
Updating a ServiceInstance for an RDS failed. Does it support updates?

### ISSUE THREAD

**Issue by lcostea** [awslabs/aws-servicebroker#54]
**Describe the bug**
I tried to change the instance type of a Postgres RDS provision with a ServiceInstance from t2.medium to t2.large. The error that I got was:
```
Message:               ServiceBroker returned a failure for update call; update will not be retried: 
Status: 400; 
ErrorMessage: <nil>; 
Description: The service plan 6ad024ee-a01d-56d2-97f4-84bbdfabdcde has no updatable parameters.; 
ResponseError: <nil>
```

**To Reproduce**
Create a ServiceInstance for a Postgres RDS. 
After provisioning is done, try to modify the instance type. 
You will see you will receive an error. Another problem is you can't use that ServiceInstance anymore, after it failed no more ServiceBinding can be created.

**Expected behavior**
Update should be working, the changes should be propagated to the RDS instance, or I should not be allowed to modify the ServiceInstance. 
I also realise this might be a feature request and not a bug.
I should still be able to create ServiceBinding even after the update failed because the RDS has no issues.

**Environment (please complete the following information):**
Kubernetes Kops Cluster on AWS
Kubernetes version: 1.10.5
Broker Version: 1.0.0-beta.2

**Comment by vsomayaji** [comment]
@jaymccon right now, the [`rds`](https://github.com/awslabs/aws-servicebroker/blob/master/templates/rdsmysql/template.yaml) does not expose any updatable parameters. At a minimum, I'd say `DBInstanceClass` and `AllocatedStorageAndIops` should be updatable

@lcostea I'll take a look into why binding fails after an unsuccessful update.

**Comment by vsomayaji** [comment]
@lcostea I was able to reproduce the binding failure. After an unsuccessful update, the service instance is left in status `Failed`, which causes the binding to fail with `ErrorInstanceNotReady`. 

Based on https://github.com/kubernetes-incubator/service-catalog/issues/1487, you should be able to update the service instance to its original configuration to restore its status to `Ready`. However, in the case when there are no updatable parameters, our code doesn't currently allow this. I'll create a PR to get this addressed. Thanks!
