### ISSUE TITLE
Helm-Documentation is missing mentioning "ClusterServiceBroker"

### ISSUE THREAD

**Issue by Gottox** [awslabs/aws-servicebroker#55]
**Describe the bug**
I'm unable to install aws-servicebroker with the provided helm documentation

**To Reproduce**
Assuming helm and tiller is already installed:
1. `helm repo add aws-sb https://awsservicebroker.s3.amazonaws.com/charts`
2. `helm install aws-sb/aws-servicebroker --name aws-servicebroker --namespace aws-sb --version 1.0.0-beta.2`
3. Errormessage appears:
```
Error: validation failed: unable to recognize "": no matches for kind "ClusterServiceBroker" in version "servicecatalog.k8s.io/v1beta1"
```

**Expected behavior**
Helm successfully deploys the servicebroker

**Screenshots**

**Environment (please complete the following information):**
 - Application Platform: Kubernetes
 - Application Platform Version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"archive", BuildDate:"2018-10-07T09:55:32Z", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T15:54:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
 - Broker Version 1.0.0-beta.2
**Additional context**
Kubernetes deployed via kops on AWS.

**Comment by jaymccon** [comment]
@Gottox This looks like [kubernetes service catalog](https://kubernetes.io/docs/tasks/service-catalog/) is not installed

**Comment by Gottox** [comment]
Thanks, I already fixed the issue for myself. Nontheless, I'm considering that a documentation issue.

**Comment by jaymccon** [comment]
Can you clarify on where you feel the docs could be improved ? From my tests following the documentation works as expected.

**Comment by rafilkmp3** [comment]
@jaymccon  docs are not explicit about install service-broker, Im had same issue and fixed because this issue
