### ISSUE TITLE
No example for custom resources

### ISSUE THREAD

**Issue by winjer** [awslabs/aws-servicebroker#64]
**Describe the bug**

In the Documentation README it says there is an example custom spec file at:

`/examples/example-spec.yaml`

There is not.

**To Reproduce**

Go to https://github.com/awslabs/aws-servicebroker/tree/master/docs and scroll to the end

**Expected behavior**

Clicking the Example -spec.yaml file link does not 404

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**

**Comment by joshkurz** [comment]
Any update on this? is this a feature that is coming or is it in place? A simple example would be very nice to build from.

**Comment by jaymccon** [comment]
@joshkurz @winjer the docs have been updated to include an example template with inline comments
