### ISSUE TITLE
Support MySQL 8.0

### ISSUE THREAD

**Issue by Gottox** [awslabs/aws-servicebroker#65]
**Is your feature request related to a problem? Please describe.**
AWS RDS has added support for mysql 8.0. The service broker does not support this according to [rdsmysql/template.yaml](https://github.com/awslabs/aws-servicebroker/blob/c3be5bc3c30fc51797f82985b1063ffb93638352/templates/rdsmysql/template.yaml).

**Describe the solution you'd like**
It would be great if the service broker would add support for requesting mysql 8.0 instances.

**Comment by jaymccon** [comment]
@Gottox Thanks for pointing this one out, we'd like to get better at auto-updating these kind of things, but for the time being I've manually put in an update with the latest minor versions in ddc2d6f002f03fa3c23155eea200ae5fca20d29d
