### ISSUE TITLE
Description: Failed to create the CloudFormation stack:

### ISSUE THREAD

**Issue by pierreozoux** [awslabs/aws-servicebroker#76]
**Describe the bug**
Trying to deploy a MySQL service.

**Additional context**
E1204 17:30:51.289739       1 util.go:269] Status: 500; ErrorMessage: <nil>; Description: Failed to create the CloudFormation stack: AccessDenied: Access denied
	status code: 403, request id: 5862fc30-f7ea-11e8-9bed-e94e95f61919; ResponseError: <nil>

I think I have an issue with the ServiceBroker role. Do you have hints on how to further investigate that?

thanks!

**Comment by jaymccon** [comment]
That looks like the `cloudformation.CreateStack` api got denied. 

If you check the broker logs there should be some info about what role was being used in the call. look for lines with `Assuming role arn ` or `Parameter 'target_role_name' not set. Not assuming role.`. Lines just after `Running as caller identity ` should tell you the default role the broker is using for operations (it will also use this role to call `CreateStack` if `Parameter 'target_role_name' not set. ` is in the logs.

**Comment by pierreozoux** [comment]
I found my issue.
In our fork of the QuickStart, we have different profiles for different nodes, and I didn't check that. It is now fixed.
Thanks!
