### ISSUE TITLE
Unable to provision s3 bucket

### ISSUE THREAD

**Issue by jgeorge300** [awslabs/aws-servicebroker#87]
**Describe the bug**
When attempting to provision a S3 bucket with the SB in my PCF environment, I receive the following error:
`$ cf create-service s3-example plana s3-service
Creating service instance s3-service in org ORG / space SPACE as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: Failed to create the CloudFormation stack: ValidationError: S3 error: Access Denied
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
        status code: 400, request id: 2f7ffbe4-1052-11e9-8f58-c97c40b8f191
`

The broker had the following messages in the log:
`[APP/PROC/WEB/0] [ERR] I0104 19:23:55.667990 48 awsbroker.go:208] Client OSB API Version: "2.13"
[APP/PROC/WEB/0] [ERR] I0104 19:23:55.673905 48 util.go:174] Overrides: 'map[region:us-east-1]'.
[APP/PROC/WEB/0] [ERR] I0104 19:23:55.677847 48 util.go:194] Did not find 'aws_access_key' and 'aws_secret_key' in params, using default chain.
[APP/PROC/WEB/0] [ERR] I0104 19:23:55.677901 48 aws_sdk.go:71] Parameter 'target_role_name' not set. Not assuming role.
[APP/PROC/WEB/0] [ERR] E0104 19:23:55.822105 48 util.go:269] Status: 500; ErrorMessage: <nil>; Description: Failed to create the CloudFormation stack: ValidationError: S3 error: Access Denied
[APP/PROC/WEB/0] [ERR] For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
[APP/PROC/WEB/0] [ERR] status code: 400, request id: 470d33d2-1056-11e9-8e73-673b8c90e28b; ResponseError: <nil>
[RTR/0] [OUT] aws-sb.apps.np1. - [2019-01-04T19:23:55.501+0000] "PUT /v2/service_instances/e323bc4a-d280-40b0-a568-79cf50f6dc7d?accepts_incomplete=true HTTP/1.1" 500 362 266 "-" "HTTPClient/1.0 (2.8.3, ruby 2.4.2 (2017-09-14))" "10.0.0.11:30982" "10.0.32.24:61056" x_forwarded_for:"XX.XX.XX.XX, 10.0.0.11" x_forwarded_proto:"https" vcap_request_id:"26e2fbb5-9774-45e7-6b3b-e6120a76400a" response_time:0.32378416 app_id:"7434b9db-d97f-4c88-af32-53a3d71a14e2" app_index:"0" x_b3_traceid:"0126128052eef9f7" x_b3_spanid:"0126128052eef9f7" x_b3_parentspanid:"-"
[RTR/2] [OUT] aws-sb.apps.np1. - [2019-01-04T19:23:58.750+0000] "DELETE /v2/service_instances/e323bc4a-d280-40b0-a568-79cf50f6dc7d?accepts_incomplete=true&plan_id=205b6bf2-4618-5387-8462-d6337e63aa4b&service_id=ee7a9dca-274e-5131-9eb0-88f045e8fab1 HTTP/1.1" 410 0 90 "-" "HTTPClient/1.0 (2.8.3, ruby 2.4.2 (2017-09-14))" "10.0.0.11:10340" "10.0.32.24:61056" x_forwarded_for:"XX.XX.XX.XX, 10.0.0.11" x_forwarded_proto:"https" vcap_request_id:"5e906576-d6c7-4e94-5792-4413530f947e" response_time:0.174224592 app_id:"7434b9db-d97f-4c88-af32-53a3d71a14e2" app_index:"0" x_b3_traceid:"856e51ccf10c43c2" x_b3_spanid:"856e51ccf10c43c2" x_b3_parentspanid:"-"
[APP/PROC/WEB/0] [ERR] I0104 19:23:58.926500 48 awsbroker.go:208] Client OSB API Version: "2.13"
[APP/PROC/WEB/0] [ERR] I0104 19:23:58.926584 48 apisurface.go:207] Unable to retrieve originating identity - unable to find originating identity
[APP/PROC/WEB/0] [ERR] E0104 19:23:58.931522 48 util.go:269] Status: 410; ErrorMessage: <nil>; Description: The service instance e323bc4a-d280-40b0-a568-79cf50f6dc7d was not found.; ResponseError: <nil>`

**To Reproduce**
Install tile and use example s3 yaml
Use cf cli to try and provision a s3 bucket

**Environment (please complete the following information):**
 - Application Platform: Pivotal Cloud Foundry
 - Application Platform Version: 2.2
 - Broker Version 1.0-b3

**Additional context**
Set access and secret rather than a role. Permissions for the account has the policy listed in the documentation.

**Comment by jaymccon** [comment]
I have been unable to replicate this, can you please validate that the IAM roles used are matching the documentation, and try again using the latest release, which has additional logging that should shed light on exactly which permission is lacking.

**Comment by jgeorge300** [comment]
I've upgraded to 1.0-b4. I set the logging to 10. I'm still experiencing the issue. I even tried giving the service account full permissions to CFN and S3, but it still gives the S3 Access Error.

**Comment by chiefy** [comment]
@jgeorge300 did you ever figure this out? Having similar errors trying to create an s3 bucket cross-account in AWS.

**Comment by jgeorge300** [comment]
@chiefy Yes, I resolved it. It was a configuration/setup issue. I'm using a custom s3 bucket for my plans and it didn't match what was expected.

**Comment by nikileshsa** [comment]
@jgeorge300 Can you please shed some more light on your configuration/setup that resulted in this error? I am getting a S3 access denied error as well and want to understand if there is a common root cause.

**Comment by jgeorge300** [comment]
@nikileshsa I'm not currently using this broker so I don't recall exactly what needs to be done. From what I recall, the docs aren't clear on how to fully set-up a local config. I ended mirroring the default configs locally and started removing those items I did not need,
