### ISSUE TITLE
PreventDeletion is gone and is not present on the S3 Bucket (template)

### ISSUE THREAD

**Issue by geNAZt** [awslabs/aws-servicebroker#88]
**Describe the bug**
We deploy temporary buckets and want to be able to tell CloudFormation to delete those when we delete the ServiceInstance. I was happy to see the PreventDeletion option in the readme of the S3 Bucket template, but the template itself seems to be reverted to some older version as the parameter is not there

**To Reproduce**
Deploy a S3 bucket with PreventDeletion set to false

**Expected behavior**
The S3 bucket is created and gets deleted after removing the service instance

**Screenshots**

**Environment (please complete the following information):**
 - Application Platform: k8s
 - Application Platform Version: k8s 1.10.x (latest bugfix)
 - Broker Version 1.0.0-beta.3

**Additional context**

**Comment by TheKangaroo** [comment]
same problem here with beta (1.0.0-beta.4)
Would love to see this fixed, since we need the broker for temporary buckets too.

**Comment by jaymccon** [comment]
the default catalog in S3 should now be in sync with the master branch (and have the PreventDeletion option)

**Comment by chiefy** [comment]
@jaymccon confused - I see `DeletionPolicy` but not `PreventDeletion` in the latest templates for s3?

**Comment by jaymccon** [comment]
@chiefy my bad, can you check again please

**Comment by chiefy** [comment]
@jaymccon thank you sir!
